// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmmzgeyrdkbvsmsjbjsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbXpnZXlyZGtidnNtc2pianNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzMwMjQsImV4cCI6MjA3MzMwOTAyNH0.OX3CSxQhryav25W_ZtX6tK6LrQA-Kv2BReOqy7SuhHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});